const roomTypes = {
  GET_ROOMS_DATA: 'GET_ROOMS_DATA',
  STORE_ROOMS_DATA: 'STORE_ROOMS_DATA',
  GET_ROOM_DATA_BY_ID: 'GET_ROOM_DATA_BY_ID',
  STORE_ROOM_DATA: 'STORE_ROOM_DATA',
  RESERVE_ROOM: 'RESERVE_ROOM',
  STORE_RESERVE_STATUS: 'STORE_RESERVE_STATUS'
}

export default roomTypes
